// Code generated by MockGen. DO NOT EDIT.
// Source: bl/annotationService/annotattionRepo/anotattionRepoAdapter/anotattionRepoAdapter.go

// Package mock_repo_adapter is a generated GoMock package.
package mock_repo_adapter
