// Code generated by MockGen. DO NOT EDIT.
// Source: bl/userService/userService.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIUserService is a mock of IUserService interface.
type MockIUserService struct {
	ctrl     *gomock.Controller
	recorder *MockIUserServiceMockRecorder
}

// MockIUserServiceMockRecorder is the mock recorder for MockIUserService.
type MockIUserServiceMockRecorder struct {
	mock *MockIUserService
}

// NewMockIUserService creates a new mock instance.
func NewMockIUserService(ctrl *gomock.Controller) *MockIUserService {
	mock := &MockIUserService{ctrl: ctrl}
	mock.recorder = &MockIUserServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIUserService) EXPECT() *MockIUserServiceMockRecorder {
	return m.recorder
}

// ChangeUserRoleByLogin mocks base method.
func (m *MockIUserService) ChangeUserRoleByLogin(login string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangeUserRoleByLogin", login)
	ret0, _ := ret[0].(error)
	return ret0
}

// ChangeUserRoleByLogin indicates an expected call of ChangeUserRoleByLogin.
func (mr *MockIUserServiceMockRecorder) ChangeUserRoleByLogin(login interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeUserRoleByLogin", reflect.TypeOf((*MockIUserService)(nil).ChangeUserRoleByLogin), login)
}
