// Code generated by MockGen. DO NOT EDIT.
// Source: bl/anotattionTypeService/anotattionTypeService.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	models "annotater/internal/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIAnotattionTypeService is a mock of IAnotattionTypeService interface.
type MockIAnotattionTypeService struct {
	ctrl     *gomock.Controller
	recorder *MockIAnotattionTypeServiceMockRecorder
}

// MockIAnotattionTypeServiceMockRecorder is the mock recorder for MockIAnotattionTypeService.
type MockIAnotattionTypeServiceMockRecorder struct {
	mock *MockIAnotattionTypeService
}

// NewMockIAnotattionTypeService creates a new mock instance.
func NewMockIAnotattionTypeService(ctrl *gomock.Controller) *MockIAnotattionTypeService {
	mock := &MockIAnotattionTypeService{ctrl: ctrl}
	mock.recorder = &MockIAnotattionTypeServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIAnotattionTypeService) EXPECT() *MockIAnotattionTypeServiceMockRecorder {
	return m.recorder
}

// AddAnottationType mocks base method.
func (m *MockIAnotattionTypeService) AddAnottationType(anotattion *models.MarkupType) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddAnottationType", anotattion)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddAnottationType indicates an expected call of AddAnottationType.
func (mr *MockIAnotattionTypeServiceMockRecorder) AddAnottationType(anotattion interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddAnottationType", reflect.TypeOf((*MockIAnotattionTypeService)(nil).AddAnottationType), anotattion)
}

// DeleteAnotattionType mocks base method.
func (m *MockIAnotattionTypeService) DeleteAnotattionType(id uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAnotattionType", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAnotattionType indicates an expected call of DeleteAnotattionType.
func (mr *MockIAnotattionTypeServiceMockRecorder) DeleteAnotattionType(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAnotattionType", reflect.TypeOf((*MockIAnotattionTypeService)(nil).DeleteAnotattionType), id)
}

// GetAnottationTypeByID mocks base method.
func (m *MockIAnotattionTypeService) GetAnottationTypeByID(id uint64) (*models.MarkupType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAnottationTypeByID", id)
	ret0, _ := ret[0].(*models.MarkupType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAnottationTypeByID indicates an expected call of GetAnottationTypeByID.
func (mr *MockIAnotattionTypeServiceMockRecorder) GetAnottationTypeByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAnottationTypeByID", reflect.TypeOf((*MockIAnotattionTypeService)(nil).GetAnottationTypeByID), id)
}
