// Code generated by MockGen. DO NOT EDIT.
// Source: bl/NN/NNAdapter/NNmodelhandler/NNmodelhandler.go

// Package mock_nn_model_handler is a generated GoMock package.
package mock_nn_model_handler

import (
	nn_model_handler "annotater/internal/bl/NN/NNAdapter/NNmodelhandler"
	models_dto "annotater/internal/models/dto"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIModelHandler is a mock of IModelHandler interface.
type MockIModelHandler struct {
	ctrl     *gomock.Controller
	recorder *MockIModelHandlerMockRecorder
}

// MockIModelHandlerMockRecorder is the mock recorder for MockIModelHandler.
type MockIModelHandlerMockRecorder struct {
	mock *MockIModelHandler
}

// NewMockIModelHandler creates a new mock instance.
func NewMockIModelHandler(ctrl *gomock.Controller) *MockIModelHandler {
	mock := &MockIModelHandler{ctrl: ctrl}
	mock.recorder = &MockIModelHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIModelHandler) EXPECT() *MockIModelHandlerMockRecorder {
	return m.recorder
}

// GetModelResp mocks base method.
func (m *MockIModelHandler) GetModelResp(req nn_model_handler.ModelRequest) ([]models_dto.Markup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetModelResp", req)
	ret0, _ := ret[0].([]models_dto.Markup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetModelResp indicates an expected call of GetModelResp.
func (mr *MockIModelHandlerMockRecorder) GetModelResp(req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetModelResp", reflect.TypeOf((*MockIModelHandler)(nil).GetModelResp), req)
}
