model:
  route: "http://0.0.0.0:5000/pred"

report_storage:
  report_creator_path: ../../../reportsCreator
  report_storage: ../../../reports
  report_ext: .pdf

document_storage:
  document_path: ../../../documents
  document_ext: .pdf

database:
  host: localhost
  user: andrew
  password: 1
  database: postgres
  port: 5432


http_server:
  addr: "0.0.0.0:8080"
  read_timeout: 40s
  write_timeout: 30s
  idle_timeout: 40s

logger:
  log_level: INFO
  output_filepath : ../../logs/log
  use_file: false
  log_format: "[%lvl%]: %time% - %msg%\n"
  timestamp_format : "2006-01-02 15:04:05"
  output_format : text

