// Code generated by MockGen. DO NOT EDIT.
// Source: bl/documentService/documentRepo/documentRepoAdapter/documentRepoAdapter.go

// Package mock_repo_adapter is a generated GoMock package.
package mock_repo_adapter
